### ISSUE TITLE
Doesn’t work with Less 2.1.0

### ISSUE THREAD

**Issue by vnys** [less/less-plugin-npm-import#4]
This plugin stopped working with Less 2.1.0 when using the promise syntax.

``` less
@import (less, reference) 'npm://npm-import-plugin-test/file.css';
div:extend(.test_file_css) { }
```

``` js
    var file = fs.readFileSync('css/styles.less', 'utf8'),
        options = { plugins: [ npmImport ] },
        log = console.log.bind(console);

    // Works with Less 2.0.0 but in 2.1.0 it returns "[TypeError: undefined is not a function]"
    less.render(file, options)
        .then(log)
        .catch(log);


    // Works with Less 2.1.0
    less.render(file, options, function(error, output) {
        log(error || output);
    });
```

Test repo at https://github.com/batfink/less-bug
